#!/usr/bin/env bash
# Resolves Konflux onboarding pipeline bundle digests for a given build-definitions
# git revision (Quay tag = BUILD_TAG used by hack/build-and-push.sh), writes a
# pipelines input file, runs generate-trusted-sources.sh, and optionally runs the
# konflux-ci operator head test.
#
# Usage:
#   BUILD_DEFINITIONS_REV=013feda32b2f3abc664ad7e2c18ab579e60dd9df ./scripts/align-onboarding-trusted-sources.sh
#
# Optional:
#   OUTPUT_PIPELINES   default: onboarding-pipeline-bundles.generated.yaml (gitignored)
#   DATA_BUNDLES_REF   default: oci::quay.io/konflux-ci/tekton-catalog/data-acceptable-bundles:latest
#   TRUSTED_OUTPUT     default: ./data/trusted-sources.yaml
#   KONFLUX_CI_ROOT    if set, runs go test for TestOnboardingPipelineTaskBundlesMatchTrustedTasksCatalogHead
#   SKIP_GENERATE      if set to 1, only write OUTPUT_PIPELINES (no generate, no test)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${REPO_ROOT}"

: "${BUILD_DEFINITIONS_REV:?BUILD_DEFINITIONS_REV is required (build-definitions / catalog git SHA used as Quay pipeline bundle tag)}"

OUTPUT_PIPELINES="${OUTPUT_PIPELINES:-onboarding-pipeline-bundles.generated.yaml}"
if [[ "${OUTPUT_PIPELINES}" != /* ]]; then
  OUTPUT_PIPELINES="${REPO_ROOT}/${OUTPUT_PIPELINES}"
fi
DATA_BUNDLES_REF="${DATA_BUNDLES_REF:-oci::quay.io/konflux-ci/tekton-catalog/data-acceptable-bundles:latest}"
TRUSTED_OUTPUT="${TRUSTED_OUTPUT:-${REPO_ROOT}/data/trusted-sources.yaml}"
if [[ "${TRUSTED_OUTPUT}" != /* ]]; then
  TRUSTED_OUTPUT="${REPO_ROOT}/${TRUSTED_OUTPUT}"
fi
QUAY_NS="${QUAY_NS:-quay.io/konflux-ci/tekton-catalog}"

require_bin() {
  command -v "$1" >/dev/null 2>&1 || {
    printf 'ERROR: required command not found: %s\n' "$1" >&2
    exit 1
  }
}

require_bin skopeo
require_bin yq

retry_skopeo() {
  local ref=$1
  local attempt=1
  local max=5
  local delay=3
  while [[ "${attempt}" -le "${max}" ]]; do
    if skopeo inspect --no-tags "docker://${ref}" >/dev/null 2>&1; then
      skopeo inspect --format '{{.Digest}}' "docker://${ref}"
      return 0
    fi
    printf 'warn: skopeo inspect failed for %s (attempt %s/%s); retrying...\n' "${ref}" "${attempt}" "${max}" >&2
    sleep "${delay}"
    attempt=$((attempt + 1))
    delay=$((delay * 2))
  done
  skopeo inspect --format '{{.Digest}}' "docker://${ref}"
}

# name: pipeline repo name without pipeline- prefix mapping -> pipeline-<suffix>
declare -a ONBOARDING_PIPELINES=(
  'fbc-builder|pipeline-fbc-builder'
  'docker-build|pipeline-docker-build'
  'docker-build-oci-ta|pipeline-docker-build-oci-ta'
  'tekton-bundle-builder|pipeline-tekton-bundle-builder'
  'tekton-bundle-builder-oci-ta|pipeline-tekton-bundle-builder-oci-ta'
  'docker-build-oci-ta-min|pipeline-docker-build-oci-ta-min'
)

write_pipelines_yaml() {
  local out=$1
  {
    printf '%s\n' '# Generated by scripts/align-onboarding-trusted-sources.sh — do not commit (see .gitignore).'
    printf '%s\n' "# build-definitions revision (Quay tag): ${BUILD_DEFINITIONS_REV}"
    printf '%s\n' 'pipelines:'
    local row display_name repo
    for row in "${ONBOARDING_PIPELINES[@]}"; do
      display_name="${row%%|*}"
      repo="${row##*|}"
      local tag_ref="${QUAY_NS}/${repo}:${BUILD_DEFINITIONS_REV}"
      local digest
      digest="$(retry_skopeo "${tag_ref}")"
      printf '  - name: %s\n' "${display_name}"
      printf '    bundle: %s@%s\n' "${QUAY_NS}/${repo}" "${digest}"
    done
  } >"${out}"
  printf 'Wrote %s\n' "${out}"
}

write_pipelines_yaml "${OUTPUT_PIPELINES}"

if [[ "${SKIP_GENERATE:-0}" == "1" ]]; then
  printf 'SKIP_GENERATE=1 set; skipping generate-trusted-sources and test.\n'
  exit 0
fi

if [[ ! -f "${REPO_ROOT}/scripts/generate-trusted-sources.sh" ]]; then
  printf 'ERROR: scripts/generate-trusted-sources.sh not found at %s\n' "${REPO_ROOT}" >&2
  exit 1
fi

"${REPO_ROOT}/scripts/generate-trusted-sources.sh" \
  --pipelines-file "${OUTPUT_PIPELINES}" \
  --data-bundles-ref "${DATA_BUNDLES_REF}" \
  --output "${TRUSTED_OUTPUT}"

if [[ -n "${KONFLUX_CI_ROOT:-}" ]]; then
  if [[ ! -d "${KONFLUX_CI_ROOT}/operator" ]]; then
    printf 'ERROR: KONFLUX_CI_ROOT=%s has no operator/ subdirectory\n' "${KONFLUX_CI_ROOT}" >&2
    exit 1
  fi
  printf 'Running konflux-ci head test in %s/operator\n' "${KONFLUX_CI_ROOT}"
  (cd "${KONFLUX_CI_ROOT}/operator" && go test ./pkg/manifests/ -run TestOnboardingPipelineTaskBundlesMatchTrustedTasksCatalogHead -count=1 -v)
else
  printf 'KONFLUX_CI_ROOT not set; skipping go test. Set it to run TestOnboardingPipelineTaskBundlesMatchTrustedTasksCatalogHead.\n'
fi
